"""
Django settings for ahmee project.
Generated by 'django-admin startproject' using Django.
"""

from pathlib import Path

# المسار الأساسي للمشروع
BASE_DIR = Path(__file__).resolve().parent.parent

# مفتاح الأمان (⚠️ غيّره في بيئة الإنتاج)
SECRET_KEY = 'django-insecure-ضع_مفتاحك_هنا'

# ⚠️ لا تستخدم التصحيح (DEBUG) في بيئة الإنتاج
DEBUG = True

ALLOWED_HOSTS = []


# التطبيقات المثبتة
INSTALLED_APPS = [
    'django.contrib.admin',          # لوحة التحكم
    'django.contrib.auth',           # نظام التوثيق
    'django.contrib.contenttypes',   # إدارة أنواع المحتوى
    'django.contrib.sessions',       # الجلسات
    'django.contrib.messages',       # الرسائل
    'django.contrib.staticfiles',    # الملفات الثابتة (CSS, JS, صور)

    # التطبيقات الخاصة بالمشروع
    'Accounts',   # تطبيق الحسابات
    'Courses',    # تطبيق الدورات
    'Booking',    # تطبيق الحجز والدفع
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ahmee.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # تعريف مسار مجلد القوالب الرئيسي
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # لدعم MEDIA
            ],
        },
    },
]

WSGI_APPLICATION = 'ahmee.wsgi.application'


# قاعدة البيانات (SQLite بشكل افتراضي – يفضل تعدلها عند الإنتاج)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# التحقق من كلمات المرور
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# إعدادات اللغة والتوقيت
LANGUAGE_CODE = 'ar'              # اللغة بالعربية
TIME_ZONE = 'Asia/Riyadh'         # التوقيت الرياض
USE_I18N = True
USE_TZ = True


# ============================
# إعدادات الملفات الثابتة STATIC
# ============================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']   # مجلد static الرئيسي للمشروع
STATIC_ROOT = BASE_DIR / 'staticfiles'     # مجلد لتجميع الملفات وقت الإنتاج (collectstatic)

# ============================
# إعدادات الملفات المرفوعة MEDIA
# ============================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# الإعداد الافتراضي للمفتاح الأساسي
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
